### ISSUE TITLE
[BS] Build server 

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone-sdk#11]
### Configuration / Prerequisites:

  - [x] target platform
  - [x] GIT repositories (and branch names)
  - [x] target product (or plugin) name
  
### General build workflow:

  - [x] create workspace
  - [x] configure target platform (ZIP download)
  - [x] pull GIT repos (branches)
  - [x] import product (copy from GIT tree?)
  - [x] find product contents/dependencies
  - [ ] find plugin dependencies -> import -> loop
  - [x] export/build
  
### User interface

  - [x] list of build configurations (actions: new, remove)
  - [x] associate with current user + filter list
  - [x] detail
      - [x] name
      - [x] product name
      - [x] list of SCM repos (add/remove)
      - [x] list of target platform entries (add/remove)
      - [x] download link (servlet)
  - [ ] list of builds (of a configuration)
      - [x] time
      - [x] status: running(?), success, failed
      - [ ] progress
  - [ ] detail
      - [ ] time, status
      - [x] console log (?)
      - [x] list of errors from logs.zip (per bundle)

### TODO

  - [ ] !!! mein SSL rsa_id.pub von mapzone auf github (alle wären ich)
  - [ ] ./m2 im mapzone root account (alle nehmen dasselbe, und ein fehler geht nie wieder weg)

  - [ ] Source mit bauen? einpacken?
  - [ ] check Controller /login (panel filter)
  - [ ] no SCM and no target -> should generate an error
  - [ ] SCM branches
  - [ ] no bundle found (ScmStrategie.installBundleSource())
  - [ ] (git) command errors (return code)
  - [ ] buildrunner exceptions (return code + exception text)
  - [ ] besserer progress
