### ISSUE TITLE
[OSM] Initial version

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone-sdk#8]
### API Import Workflow (Jörg)

  - [x] tag filter selection
  - [x] select bounding box in already shown map resp. use zoomed in map as bounding box
  - [x] retrieve all tags in context of bounding box / entity (bbox?)
  - [x] show tags in table or tree: proposal
  - [x] select/unselect tags (preview in map required?)
  - [x] import all features having at least one of the selected tags

### TODO

  - additional/alternatively select geopolitical entity either in context of bounding box or without bounding box, i.e. countries, federal states, districts etc.
